services:
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
  app:
    image: 'ghcr.io/christoph-sens/pdf-generator:v1.0'
    ports:
        -   '8080:8080'
    depends_on:
        -   database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword


