services:
  database:
    image: 'postgres:16.3'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
  app:
    image: 'ghcr.io/christoph-sens/pdf-generator:1.1.1@sha256:51c81edd45e9eb75ab7a1591baa14e74fd2c347948253b678b01112008b30c18'
    ports:
        -   '8080:8080'
    depends_on:
        -   database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword


