name: Dependabot auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  # Shared job, see https://github.com/christoph-sens/ci-workflows
  auto-merge:
    uses: christoph-sens/ci-workflows/.github/workflows/dependabot-auto-merge.yml@cc1be9dcb6c167bd955c3a4598bdcb7922316d34 # v1.1.1
